apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: sbwe3onxo-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/sbwe3onxo-java-quarkus-gitops